# dimagi-clockify-cli config
---
# Get your API key at https://dimagi.clockify.me/user/settings
api_key: a1b2c3d4e5f6g7h8i9j0

buckets:
#   NAME:
#     description: DESCRIPTION
#     project: PROJECT
#     task: TASK
#     tags: [TAG]

  all_hands:
    description: Dimagi All-Hands
    project: SolTech Overhead
    task: SolTech - Other / All
    tags: [Overhead]

  gtd_meeting:
    description: Weekly GTD Meeting
    project: SolTech Overhead
    task: SolTech - Solutions
    tags: [Overhead]

  new_dev:
    description: Non-project dev work
    project: Sol Delivery Work
    task: New Product Development
    tags: [Overhead]

  tdh:
    description: Tdh Burkina Faso self-hosting
    project: Sol Client Work
    task: SolTech - Solutions
    tags: [Terre des homme:Burkina - Local Server Set up and Migration]

# You don't need to change this unless Clockify is hosted on a custom
# domain. Note: `base_url` includes "/api/v1/"
base_url: https://api.clockify.me/api/v1/
